server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gateway:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: nginx_1
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_paris_1
          host: nginx_paris_1
          filename: /var/log/nginx/json_access.log
          __path__: /var/log/nginx-paris-1/json_access.log
      - targets:
        - localhost
        labels:
          job: nginx_paris_2
          host: nginx_paris_2
          filename: /var/log/nginx/json_access.log
          __path__: /var/log/nginx-paris-2/json_access.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time_iso8601
      - timestamp:
          source: timestamp
          format: RFC3339
          action_on_failure: 'skip'
      - static_labels:
          filename: /var/log/nginx/json_access.log
          foo: bar
          pipeline: test